import nodemailer from 'nodemailer';

import { NextFunction, Response, Request } from 'express';

export const sendEmail = async (
  firstName: any,
  emailId: any,
  autoGenerate: any,
) => {
  let transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: 'shubh.mourya57@gmail.com',
      pass: 'djistckuwystfjlf',
    },
  });
  var mailOptions = {
    from: 'shubh.mourya57@gmail.com',
    to: emailId,
    subject: 'Registeration code',
    text: 'hii this is your autogenerate password ' + autoGenerate,
  };
  transporter.sendMail(mailOptions, function (err: any, info: any) {
    if (err) {
      {
        console.log(err);
      }
    }

    console.log('data send');
  });
};
export const sendEmailFortenant = async (
  first_name: any,
  email: any,
  autoGenerate: any,
) => {
  let transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: 'shubh.mourya57@gmail.com',
      pass: 'djistckuwystfjlf',
    },
  });
  var mailOptions = {
    from: 'shubh.mourya57@gmail.com',
    to: email,
    subject: 'Registeration code',
    text: ' this is your autogenerate tenant password ' + autoGenerate,
  };
  transporter.sendMail(mailOptions, function (err: any, info: any) {
    if (err) {
      {
        console.log(err);
      }
    }
    console.log('your Autogenerated password has been sent on your email id');
  });
};
// ---------------------------
